# Create Dummies

In [1]:
import pandas as pd
crash3 = pd.read_csv('crash_v2.csv')

# Drop Second impact as they are almost all the same as First Impact

In [2]:
match_count = (crash3['First Impact'] == crash3['Second Impact']).sum()

print(f"Number of rows where 'First Impact' matches 'Second Impact': {match_count}")

Number of rows where 'First Impact' matches 'Second Impact': 167783

In [3]:
categorical_columns = crash3.select_dtypes(include=['object']).columns
categorical_columns

Index(['Crash Date/Time', 'Report Number', 'ACRS Report Type',
       'Cross-Street Type', 'Driver At Fault', 'Injury Severity',
       'Parked Vehicle', 'Location', 'Collision', 'Turn', 'Light Conditions',
       'Substance', 'Distraction', 'Conditions', 'Movement', 'Body',
       'Traffic Signs', 'First Impact', 'Second Impact', 'Crash Time',
       'Distance_Bin'],
      dtype='object')

In [4]:
dummy_collision = pd.get_dummies(crash3['Collision'], prefix='Collision')
dummy_collision

,Collision_Angle Collision,Collision_Head-On Collision,Collision_Other,Collision_Same Direction,Collision_Single Vehicle,Collision_Unknown
0,0,0,0,1,0,0
1,0,0,0,1,0,0
2,0,0,0,1,0,0
3,0,0,0,1,0,0
4,0,1,0,0,0,0
...,...,...,...,...,...,...
172100,0,1,0,0,0,0
172101,0,1,0,0,0,0
172102,0,0,0,0,1,0
172103,0,1,0,0,0,0
172104,0,1,0,0,0,0

In [5]:
dummy_street = pd.get_dummies(crash3['Cross-Street Type'], prefix='Street')
dummy_street

,Street_County,Street_Government,Street_Interstate (State),Street_Maryland (State),Street_Municipality,Street_Off Road,Street_Other Public Roadway,Street_Ramp,Street_Service Road,Street_US (State),Street_Unknown
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
172100,1,0,0,0,0,0,0,0,0,0,0
172101,1,0,0,0,0,0,0,0,0,0,0
172102,1,0,0,0,0,0,0,0,0,0,0
172103,0,0,0,0,0,1,0,0,0,0,0
172104,0,0,0,0,0,1,0,0,0,0,0

In [6]:
dummy_fault = pd.get_dummies(crash3['Driver At Fault'], prefix='Fault')
dummy_fault

        Fault_No  Fault_Unknown  Fault_Yes
0              0              0          1
1              1              0          0
2              1              0          0
3              0              0          1
4              1              0          0
...          ...            ...        ...
172100         0              0          1
172101         1              0          0
172102         0              0          1
172103         0              0          1
172104         0              0          1

[172105 rows x 3 columns]

In [7]:
dummy_parked = pd.get_dummies(crash3['Parked Vehicle'], prefix='Parked')
dummy_parked

        Parked_No  Parked_Yes
0               1           0
1               1           0
2               1           0
3               1           0
4               1           0
...           ...         ...
172100          1           0
172101          1           0
172102          1           0
172103          1           0
172104          1           0

[172105 rows x 2 columns]

In [8]:
dummy_turn = pd.get_dummies(crash3['Turn'], prefix='Turn')
dummy_turn

        Turn_ No Turn  Turn_Left Turn  Turn_No Turn  Turn_Right Turn
0                   0               0             1                0
1                   0               0             1                0
2                   0               0             1                0
3                   0               0             1                0
4                   0               0             1                0
...               ...             ...           ...              ...
172100              0               1             0                0
172101              0               1             0                0
172102              0               0             1                0
172103              0               0             1                0
172104              0               0             1                0

[172105 rows x 4 columns]

In [9]:
dummy_light = pd.get_dummies(crash3['Light Conditions'], prefix='Light')
dummy_light

,Light_Dark,Light_Dawn,Light_Daylight,Light_Dusk,Light_Other,Light_Unknown
0,1,0,0,0,0,0
1,1,0,0,0,0,0
2,1,0,0,0,0,0
3,1,0,0,0,0,0
4,1,0,0,0,0,0
...,...,...,...,...,...,...
172100,1,0,0,0,0,0
172101,1,0,0,0,0,0
172102,1,0,0,0,0,0
172103,0,0,1,0,0,0
172104,0,0,1,0,0,0

In [10]:
dummy_substance = pd.get_dummies(crash3['Substance'], prefix='Substance')
dummy_substance

,Substance_Alcohol,Substance_Combination,Substance_Illegal Drug,Substance_Medication,Substance_None Detected,Substance_Other,Substance_Unknown
0,1,0,0,0,0,0,0
1,0,0,0,0,1,0,0
2,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0
4,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...
172100,0,0,0,0,1,0,0
172101,0,0,0,0,1,0,0
172102,0,0,0,0,1,0,0
172103,0,0,0,0,1,0,0
172104,0,0,0,0,1,0,0

In [11]:
dummy_distraction = pd.get_dummies(crash3['Distraction'], prefix='Distraction')
dummy_distraction

,Distraction_Distracted,Distraction_Eating/Drinking,Distraction_No Driver,Distraction_Not Distracted,Distraction_Other Device,Distraction_Phone,Distraction_Smoking,Distraction_Unknown
0,1,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0
3,0,0,0,1,0,0,0,0
4,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...
172100,0,0,0,0,0,0,0,1
172101,0,0,0,1,0,0,0,0
172102,0,0,0,0,0,0,0,1
172103,0,0,0,0,0,0,0,1
172104,0,0,0,0,0,0,0,1

In [12]:
dummy_conditions = pd.get_dummies(crash3['Conditions'], prefix='Conditions')
dummy_conditions

,Conditions_CLOUDY,Conditions_DRY,Conditions_FOGGY,Conditions_OTHER,Conditions_SNOW,Conditions_SURFACE CONTAMINANTS,Conditions_UNKNOWN,Conditions_WET,Conditions_WIND
0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
172100,0,1,0,0,0,0,0,0,0
172101,0,1,0,0,0,0,0,0,0
172102,0,1,0,0,0,0,0,0,0
172103,1,0,0,0,0,0,0,0,0
172104,1,0,0,0,0,0,0,0,0

In [13]:
dummy_movement = pd.get_dummies(crash3['Movement'], prefix='Movement')
dummy_movement

,Movement_Crossing Lanes,Movement_Driverless Vehicle,Movement_Other,Movement_Reversing,Movement_Slowing,Movement_Starting,Movement_Stationary,Movement_Travelling Forward,Movement_Turning,Movement_Unknown
0,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
172100,0,0,0,0,0,0,0,0,1,0
172101,0,0,0,0,0,0,0,1,0,0
172102,0,0,0,0,1,0,0,0,0,0
172103,0,0,0,0,0,0,0,1,0,0
172104,0,0,0,0,0,0,0,1,0,0

In [14]:
dummy_body = pd.get_dummies(crash3['Body'], prefix='Body')
dummy_body

,Body_Bus,Body_Car,Body_Emergency,Body_Farm,Body_Heavy Truck,Body_Light Truck,Body_Motorbike,Body_Non-Emergency SV,Body_Other,Body_Pickup Truck,Body_RV,Body_SUV,Body_Van
0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
172100,0,1,0,0,0,0,0,0,0,0,0,0,0
172101,0,1,0,0,0,0,0,0,0,0,0,0,0
172102,0,1,0,0,0,0,0,0,0,0,0,0,0
172103,1,0,0,0,0,0,0,0,0,0,0,0,0
172104,0,1,0,0,0,0,0,0,0,0,0,0,0

In [15]:
dummy_signage = pd.get_dummies(crash3['Traffic Signs'], prefix='Signage')
dummy_signage

,Signage_No controls,Signage_Other,Signage_Person,Signage_Stop Sign,Signage_Traffic Signal/Lights,Signage_Warning Sign
0,0,0,0,0,1,0
1,0,0,0,0,1,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0
...,...,...,...,...,...,...
172100,0,0,0,0,1,0
172101,0,0,0,0,1,0
172102,1,0,0,0,0,0
172103,1,0,0,0,0,0
172104,1,0,0,0,0,0

In [16]:
dummy_1st_impact = pd.get_dummies(crash3['First Impact'], prefix='1st_Impact')
dummy_1st_impact

,1st_Impact_Front,1st_Impact_Left,1st_Impact_Other,1st_Impact_Rear,1st_Impact_Right,1st_Impact_Unknown
0,1,0,0,0,0,0
1,0,0,0,1,0,0
2,0,0,0,1,0,0
3,1,0,0,0,0,0
4,1,0,0,0,0,0
...,...,...,...,...,...,...
172100,1,0,0,0,0,0
172101,1,0,0,0,0,0
172102,0,0,1,0,0,0
172103,0,1,0,0,0,0
172104,0,0,0,1,0,0

In [17]:
dummies_concat = pd.concat([dummy_collision, dummy_street, dummy_fault,
                           dummy_parked, dummy_turn, dummy_light, dummy_substance,
                           dummy_distraction, dummy_conditions, dummy_movement, dummy_body,
                           dummy_signage, dummy_1st_impact], axis=1)

In [18]:
dummies_concat.head()

,Collision_Angle Collision,Collision_Head-On Collision,Collision_Other,Collision_Same Direction,Collision_Single Vehicle,Collision_Unknown,Street_County,Street_Government,Street_Interstate (State),Street_Maryland (State),...,Signage_Person,Signage_Stop Sign,Signage_Traffic Signal/Lights,Signage_Warning Sign,1st_Impact_Front,1st_Impact_Left,1st_Impact_Other,1st_Impact_Rear,1st_Impact_Right,1st_Impact_Unknown
0,0,0,0,1,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0
1,0,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,0,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,0,0,0,1,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0
4,0,1,0,0,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0

In [19]:
dummies_concat.to_csv('dummies.csv', index=False)